catalog:
  "@antfu/eslint-config": ^7.2.0
  "@changesets/cli": ^2.29.8
  "@commitlint/cli": ^20.3.1
  "@commitlint/config-conventional": ^20.3.1
  "@commitlint/types": ^20.3.1
  "@emotion/styled": ^11.13.0
  "@eslint-react/eslint-plugin": 2.10.1
  "@fontsource/inter": ^5.1.0
  "@mui/joy": 5.0.0-beta.51
  "@nanostores/react": ^1.0.0
  "@total-typescript/ts-reset": ^0.6.1
  "@types/node": ^22.13.10
  "@types/object-inspect": ^1.13.0
  "@types/qs": ^6.9.18
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  "@typescript/native-preview": 7.0.0-dev.20260128.1
  "@vitejs/plugin-react": ^5.1.3
  "@vp-tw/eslint-config": ^1.0.5
  "@vp-tw/tsconfig": ^4.0.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  commitizen: ^4.3.1
  cspell: ^9.6.2
  es-toolkit: ^1.31.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-package-json: ^0.88.2
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.19
  husky: ^9.1.7
  lint-staged: ^16.2.7
  nanostores: ^1.1.0
  npm-run-all: ^4.1.5
  object-inspect: ^1.13.4
  oxfmt: ^0.27.0
  pkg-dir: ^8.0.0
  qs: ^6.14.0
  react: ^19.0.0
  react-dom: ^19.0.0
  ts-toolbelt: ^9.6.0
  tsx: ^4.19.3
  typescript: ^5.9.3
  vite: ^5.4.21
  vite-tsconfig-paths: ^5.1.4
  vitest: ^2.1.3
  zod: ^3.24.2
overrides:
  "@eslint-react/eslint-plugin": $@eslint-react/eslint-plugin
packages:
  - "packages/*"
shellEmulator: true
trustPolicy: no-downgrade
